=== nagydani98/Xml/FurnitureStoreHandler/furniturestore.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <xs:complexType name="personBaseType">
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="furnitureBaseType">
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="colour" type="xs:string"/>
        <xs:attribute name="dimensions" type="xs:string"/>
    </xs:complexType>
    
    <xs:complexType name="saleType">
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="employeeId" type="xs:string" use="required"/>
        <xs:attribute name="furnitureId" type="xs:string" use="required"/>
        <xs:attribute name="amount" type="xs:integer" default="1"/>
    </xs:complexType>
    
    <xs:element name="store">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="team">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="employee" type="personBaseType" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="wares">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="product" type="furnitureBaseType" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="saleHistory">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sale" type="saleType" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                
            </xs:sequence>
        </xs:complexType>
        <xs:key name="employeeKey">
            <xs:selector xpath="team/employee"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:key name="productKey">
            <xs:selector xpath="wares/product"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:key name="saleKey">
            <xs:selector xpath="saleHistory/sale"/>
            <xs:field xpath="@id"/>
        </xs:key>
        
        <xs:keyref refer="employeeKey" name="seller">
            <xs:selector xpath="saleHistory/sale"></xs:selector>
            <xs:field xpath="@employeeId"></xs:field>
        </xs:keyref>
        <xs:keyref refer="productKey" name="soldWares">
            <xs:selector xpath="saleHistory/sale"></xs:selector>
            <xs:field xpath="@furnitureId"></xs:field>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== nagydani98/Xml/FurnitureStoreHandler/src/main/resources/store.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="furniturestore.xsd">  



<team>
        <employee id="lap123" name="John Doe"/>
        <employee id="la9123" name="Jane Doe"/>
    <employee id="asd56" name="BÃ©la"/>
<employee id="1234" name="Zala"/>
</team>
<wares>
        <product colour="black" dimensions="147x66" id="huhu456" name="wardrobe"/>
        <product colour="red" dimensions="147x66" id="aosk76" name="wardrobe"/>
        <product colour="blue" dimensions="147x66" id="12345" name="wardrobe"/>
    <product colour="piros" dimensions="78x5" id="4" name="valami"/>
</wares>
<saleHistory>
        <sale amount="2" employeeId="lap123" furnitureId="aosk76" id="45"/>
    <sale amount="65" employeeId="1234" furnitureId="4" id="1"/>
</saleHistory>
</store>

=== nagydani98/Xml/FurnitureStoreHandler/store.xml
<?xml version="1.0" encoding="UTF-8"?>
<store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="furniturestore.xsd">
    <team>
        <employee id="lap123" name="John Doe"/>
        <employee id="la9123" name="Jane Doe"/>
    </team>
    <wares>
        <product id="huhu456" name="wardrobe" colour="black" dimensions="147x66"/>
        <product id="aosk76" name="wardrobe" colour="red" dimensions="147x66"/>
        <product id="12345" name="wardrobe" colour="blue" dimensions="147x66"/>
    </wares>
    <saleHistory>
        <sale id="45" employeeId="lap123" furnitureId="aosk76" amount="2"/>
    </saleHistory>
</store>
